# -*- coding: utf-8 -*-
"""final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13SK98lYDc9ueurUeRsnAmpNtq46Bwa04
"""

import numpy
 
speed = [89,94,22,66,75,84,55,97]
 
x = numpy.mean(speed)
print(x)

import numpy
 
speed = [89,94,22,66,75,84,55,97]
 
x = numpy.median(speed)
print(x)

from scipy import stats
x = stats.mode(speed)
print(x)

speed = [89,94,22,66,75,84,55,97]

x = numpy.median(speed)
y = numpy.std(speed)
z = numpy.var(speed)

print(x,y,z)

import numpy

age = [99,23,44,55,35,26,77,53,22,43]

x = numpy.percentile(age,75)

print(x)

import numpy
import matplotlib.pyplot as plt

x = numpy.random.normal(5.0,1.0,1000000)

plt.hist(x,100)
plt.show()

#scatter plot

x = [5,7,8,9,7,2,2,4,6,8,11,23,22,20]

y = [99,64,27,88,66,96,35,88,55,47,99,46,57,45]

plt.scatter(x,y)
plt.show()

